// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProjetoEngSoftware.Contexts;

namespace ProjetoEngSoftware.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20200417015053_Migrations")]
    partial class Migrations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("ProjetoEngSoftware.Models.Cadastro", b =>
                {
                    b.Property<string>("login")
                        .HasColumnName("login")
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .HasColumnName("password")
                        .HasColumnType("text");

                    b.HasKey("login");

                    b.ToTable("login");
                });

            modelBuilder.Entity("ProjetoEngSoftware.Models.Etnia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_etnia")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Descricao")
                        .HasColumnName("ds_etnia")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("tb_etnia");
                });

            modelBuilder.Entity("ProjetoEngSoftware.Models.Login", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_login")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Password")
                        .HasColumnName("password")
                        .HasColumnType("text");

                    b.Property<string>("UserLogin")
                        .HasColumnName("login")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("tb_login");
                });

            modelBuilder.Entity("ProjetoEngSoftware.Models.Paciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_paciente")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnName("dt_nascimento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Nome")
                        .HasColumnName("nm_paciente")
                        .HasColumnType("text");

                    b.Property<char>("Sexo")
                        .HasColumnName("tp_sexo")
                        .HasColumnType("character(1)");

                    b.Property<int>("etnia")
                        .HasColumnName("tp_etnia")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("tb_paciente");
                });
#pragma warning restore 612, 618
        }
    }
}
